### posts API

POST http://localhost:3000/posts
Content-Type: application/json

{
    "sender": "meir",
    "message": "this is a test message"
}
###

GET http://localhost:3000/posts

###

GET http://localhost:3000/posts/6734b95f9da035039afdcd09

###

GET http://localhost:3000/posts?sender=meir

###

PUT http://localhost:3000/posts/6734b95f9da035039afdcd09
Content-Type: application/json

{
    "message": "message to update to"
}

### messages API

POST http://localhost:3000/comments
Content-Type: application/json

{
    "sender": "john_doe",
    "content": "This is a comment.",
    "postId": "6734b95f9da035039afdcd09"
}

###

GET http://localhost:3000/comments

###

GET http://localhost:3000/comments/6734b95f9da035039afdcd09

###

GET http://localhost:3000/comments/post/6734b95f9da035039afdcd09

###

PUT http://localhost:3000/comments/641c17a0b4dca222344e2f1a
Content-Type: application/json

{
    "content": "Updated comment content"
}

###

DELETE http://localhost:3000/comments/641c17a0b4dca222344e2f1a

### Users API

POST http://localhost:3000/users
Content-Type: application/json

  {
    "username": "MockUser1",
    "email": "user@awsomeDomain1.com",
    "password": "passToEncrypt"
  }
###

GET http://localhost:3000/users

###

GET http://localhost:3000/users/67487a1d94cbedc83578be7d

###
PUT http://localhost:3000/users/67488465cbda584883105a05
Content-Type: application/json

{
    "username": "myUserNameIsCool",
    "email" : "user@myDifferentAwsomeDomain.coma"
}

###
DELETE http://localhost:3000/users/67488465cbda584883105a05